B.OS/B.OS.WEB/Controllers/ClienteController.cs
using B.OS.WEB.Models;
using B.OS.WEB.Models.Services.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace B.OS.WEB.Controllers
{
	public class ClienteController : Controller
	{
		private readonly IClienteService _service;

		public ClienteController(IClienteService service)
		{
			_service = service;	
		}

		public async Task<IActionResult> Index(string search, int page = 1)
		{
			IPagedList<TabCliente> lista = null;

			try
			{		
				lista = await _service.BuscarPorTermo(search, page, 10);

				ViewBag.Search = search;
			}
			catch (Exception ex)
			{
				ViewBag.AlertaTela = 0;
				ViewBag.MensagemRetorno = "ERRO DE PROCESSAMENTO! ENTRE EM CONTATO COM O SUPORTE!";
			}

			return View(lista);
		}

		[HttpPost]
		public async Task<IActionResult> Save(TabCliente model)
		{
			ChaveValor retorno = new ChaveValor();
			retorno.Codigo = "0";

			try
			{
				if(model.IncluirAlterar == 0)
				{
					await _service.InsertAsync(model);
				}
				else
				{
					await _service.UpdateAsync(model);
				}

				retorno.Codigo = "1";
				retorno.Descricao = "DADOS CADASTRADOS COM SUCESSO!";
			}
			catch (Exception ex)
			{
				retorno.Codigo = "0";
				retorno.Descricao = "ERRO DE PROCESSAMENTO! CONTATE O SUORTE!";

				return BadRequest(retorno);
			}

			return Ok(retorno);
		}

		[HttpGet]
		public async Task<IActionResult> Remove(short id)
		{
			try
			{
				_service.DeleteAsync(id);

				TempData["AlertaTela"] = 1;
				TempData["MensagemRetorno"] = "CADASTRO REMOVIDO COM SUCESSO!";
			}
			catch (Exception ex)
			{
				TempData["AlertaTela"] = 0;
				TempData["MensagemRetorno"] = "ERRO AO DELETAR CADASTRO! CONTATE O SUPORTE!";
			}

			return Ok();
		}

		public async Task<IActionResult> Form(int incluirAlterar, int id)
		{
			TabCliente retorno = new TabCliente();

			try
			{
				//ALTERAÇÃO
				if (incluirAlterar == 1)
				{
					//BUSCAR O CADASTRO
					retorno = await _service.GetByIdAsync(id);

					//IMPORTAR PARA A TELA FORM
				}

				retorno.IncluirAlterar = incluirAlterar;
			}
			catch (Exception ex)
			{
				ViewBag.AlertaTela = 0;
				ViewBag.MensagemRetorno = "ERRO DE PROCESSAMENTO! ENTRE EM CONTATO COM O SUPORTE!";
			}

			return View("Form", retorno);
		}
	}
}

B.OS/B.OS.WEB/Controllers/FaturaController.cs
using B.OS.WEB.Models;
using B.OS.WEB.Models.Services.Interface;
using B.OS.WEB.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace B.OS.WEB.Controllers
{
	public class FaturaController : Controller
	{
		private readonly IFaturaService _serviceFatura;
		private readonly IFaturaItemService _serviceItem;

		public FaturaController(IFaturaService serviceFatura, IFaturaItemService serviceItem)
		{
			_serviceFatura = serviceFatura;
			_serviceItem = serviceItem;
		}

		public async Task<IActionResult> Index(string search, int page = 1)
		{
			IPagedList<FaturaGridViewModel> lista = null;

			try
			{
				lista = await _serviceFatura.BuscarPorTermo(search, page, 10);

				ViewBag.Search = search;
			}
			catch (Exception ex)
			{
				ViewBag.AlertaTela = 0;
				ViewBag.MensagemRetorno = "ERRO DE PROCESSAMENTO! ENTRE EM CONTATO COM O SUPORTE!";
			}

			return View(lista);
		}
	}
}

B.OS/B.OS.WEB/Controllers/OrdemServicoController.cs
using B.OS.WEB.Models;
using B.OS.WEB.Models.Services.Interface;
using B.OS.WEB.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace B.OS.WEB.Controllers
{
	public class OrdemServicoController : Controller
	{
		private readonly IOrdemServicoService _service;

		public OrdemServicoController(IOrdemServicoService service)
		{
			_service = service;
		}

		public async Task<IActionResult> Index(string search, int page = 1)
		{
			IPagedList<OSGridViewModel> lista = null;

			try
			{
				lista = await _service.BuscarPorTermo(search, page, 10);

				ViewBag.Search = search;
			}
			catch (Exception ex)
			{
				ViewBag.AlertaTela = 0;
				ViewBag.MensagemRetorno = "ERRO DE PROCESSAMENTO! ENTRE EM CONTATO COM O SUPORTE!";
			}

			return View(lista);
		}
	}
}

B.OS/B.OS.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - B.OS.WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/B.OS.WEB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ordem de Serviço</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fatura" asp-action="Index">Faturas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrdemServico" asp-action="Index">Ordem de Serviço</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Ordem de Serviço - Borges Consultoria
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>